### ISSUE TITLE
Is it possible to add colors or edit styling ?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ijgnd/anki21__reviewer_additional_card_fields#2]
Hi,

I have been using your addon for a while know as it allows me to know when a card is new or in learning or in review. But do you think it is possible to display "new" in red/bold/underlined for example ?

Thanks ! (your addon rocks !)

**Comment by ijgnd** [comment]
handling `{{info::New?}}` should be easy because it the card is not new it's empty. So it should be enough to edit the card template. wrap `{{info::New?}}` into a class like `<p class=mynew>{{info::New?}}</p>`. Then add this to the bottom of the styling:

```css
.mynew {
 color: red;
 font-weight: bold;
 text-decoration: underline;
}
```

P.S.: It's not my add-on. I just made small changes so that it works in the new version of Anki.

**Comment by thiswillbeyourgithub** [comment]
Oh great thanks ! I now have it in bold and underlined but the color doesn't seem to work. I am using cloze and tried commenting "color: black;" that was in ".card" in the default styling template but "new" stays in black :/ 

any idea ?

**Comment by ijgnd** [comment]
I don't know much about styling websites. Maybe `color: red !important;`. But who knows what this might break. maybe open a thread in the anki forum at anki.tenderapp.com or on reddit.com/r/anki about styling your card. If you do this: post all code from the styling section and front template and back template.

**Comment by thiswillbeyourgithub** [comment]
Nope, didn't work. Well it's underlined and bold and that's enough for now. Thanks for the quick help !
