### ISSUE TITLE
conditional fields stopped working on 2.1.20

### ISSUE THREAD

**Issue by JHerseth** [ijgnd/anki21__reviewer_additional_card_fields#3]
{{info-Reviews:}} works and shows what it should, but I use the same template for mobile and PC, and don't have space for the extra info on mobile.  I've used {{#info::Reviews}} {{info::Reviews}} {{/info::Reviews}} before and it worked well, but the corresponding {{#info-Reviews:}} etc does not work.  Nothing is displayed at all.

**Comment by ijgnd** [comment]
conditional replacement no longer works for `{{info-` fields of the add-on additional card fields. With <= 2.1.19 you could use e.g. `{{#info::Reviews}} {{info::Reviews}} {{/info::Reviews}}`.

the Anki creator Damien Elmes (@dae) generously adjusted source code of this add-on code and the syntax to 2.1.20 because of internal changes in 2.1.20.

As far as I see there's nothing I can do from the side of the add-on. As far as I see only few people use this add-on. But maybe other add-ons (in the future) will also use a similar functionality so that this is relevant for the main Anki?

My idea for a workaround would to to wrap `{{info-Reviews:}}` in div of a certain class and use [platform-specific-css](https://apps.ankiweb.net/docs/manual.html#platform-specific-css) and set `display: none;` for mobile?

**Comment by JHerseth** [comment]
Thanks for the explanation. Yeah, I've worked around it by using bootstraps d-none and d-md-block to only show it when screen size is above a certain limit.

**Comment by thiswillbeyourgithub** [comment]
For those with only a limited understanding of CSS, I did this do stop showing the fields on mobile :
 
* add this on the front/back template : 
`<div class = notOnMobile><u><b>{{fields you want to hide}}</div>`
* add this in the styling section
`.mobile .notOnMobile { display : none ; }`

**Comment by ijgnd** [comment]
[Here](https://anki.tenderapp.com/discussions/add-ons/40804-additional-card-fields-official-thread#comment_48181511) is a solution from the official forum using javascript by the user Guillem Palau-Salvà.

He wrote

> I actually use {{info-Lapses:}}. I do style it via javascript. You will need to add the id element on a div or span tag in the front/back template. Here's an example that hides the div tag if the card is not lapsed, and increases the opacity as lapses counts get higher).

    <div id="element">{{FiledName}}</div>

    <script>
    (function set_bg_by_lapses(){
    var lapses = parseInt('{{info-Lapses:}}');
    if (lapses== 0){
            document.getElementById("element").style.display = "none";
    } else if (lapses ==1){
        document.getElementById("element").style.backgroundColor = "rgba(255,255, 245, 0.2)";
    } else if (lapses>=2 && lapses<=4){
        document.getElementById("element").style.backgroundColor = "rgba(255,255, 245, 0.4)";
    } else if (lapses>5 && lapses<= 6){
        document.getElementById("element").style.backgroundColor = "rgba(255,255, 245, 0.7)";
    } else{
        document.getElementById("element").style.backgroundColor = "rgba(255,255, 245, 0.9)"; 
    }
    })();
    </div>
